import type { Article, Category, Product, Review } from './types';

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const categories: Category[] = [
  {
    slug: 'kitchen',
    title: 'Kitchen',
    description: 'Core tools for daily prep, serving, and cleanup.',
    image: img('photo-1556910103-1c02745aae4d'),
  },
  {
    slug: 'workshop',
    title: 'Workshop',
    description: 'Bench tools, storage, and fixtures built for real work.',
    image: img('photo-1504148455328-c376907d081c'),
  },
  {
    slug: 'tools',
    title: 'Tools',
    description: 'Hand tools worth handing down.',
    image: img('photo-1530124566582-a618bc2615dc'),
  },
  {
    slug: 'travel',
    title: 'Travel',
    description: 'Bags and kits built for decades of miles.',
    image: img('photo-1553062407-98eeb64c6a62'),
  },
  {
    slug: 'office',
    title: 'Office',
    description: 'Desk essentials with lasting craft.',
    image: img('photo-1497032628192-86f99bcd76bc'),
  },
  {
    slug: 'home',
    title: 'Home',
    description: 'Quiet objects that age with the house.',
    image: img('photo-1616486338812-3dadae4b4ace'),
  },
  {
    slug: 'outdoors',
    title: 'Outdoors',
    description: 'Gear for weather, not seasons.',
    image: img('photo-1551632811-561732d1e306'),
  },
  {
    slug: 'photography',
    title: 'Photography',
    description: 'Image-making gear with serviceable parts and timeless utility.',
    image: img('photo-1516035069371-29a1b244cc32'),
  },
  {
    slug: 'everyday-carry',
    title: 'Everyday Carry',
    description: 'Pocketable tools that earn daily trust.',
    image: img('photo-1526170375885-4d8ecf77b99f'),
  },
  {
    slug: 'coffee',
    title: 'Coffee',
    description: 'Brewing gear with replaceable seals, glass, and filters.',
    image: img('photo-1495474472287-4d71bcdd2085'),
  },
  {
    slug: 'cooking',
    title: 'Cooking',
    description: 'Heat, steel, and surfaces that improve with use.',
    image: img('photo-1506368249639-73a05d4d3072'),
  },
  {
    slug: 'writing',
    title: 'Writing',
    description: 'Pens, paper, and desk tools worth keeping.',
    image: img('photo-1517842645767-c639042777db'),
  },
  {
    slug: 'garage',
    title: 'Garage',
    description: 'Organization and maintenance gear for the long haul.',
    image: img('photo-1486262715619-67b85e0b08d3'),
  },
  {
    slug: 'camping',
    title: 'Camping',
    description: 'Field-tested gear for cold mornings and hard miles.',
    image: img('photo-1504280390367-361c6d9f38f4'),
  },
  {
    slug: 'bathroom',
    title: 'Bathroom',
    description: 'Personal care basics that avoid disposable churn.',
    image: img('photo-1600566752355-35792bedcfea'),
  },
  {
    slug: 'bedroom',
    title: 'Bedroom',
    description: 'Natural fibers and furniture that settle in for decades.',
    image: img('photo-1505693416388-ac5ce068fe85'),
  },
  {
    slug: 'garden',
    title: 'Garden',
    description: 'Repairable tools for soil, pruning, and seasons outside.',
    image: img('photo-1416879595882-3373a0480b5b'),
  },
];

export const products: Product[] = [
  {
    id: 'pt-cast-iron',
    slug: 'heirloom-cast-iron-skillet',
    title: 'Heirloom Cast Iron Skillet',
    subtitle: '12" pre-seasoned, made to cook for generations.',
    description:
      'A single-piece cast iron skillet with a polished cooking surface and pour spouts. Seasoned for immediate use, designed for a lifetime of heat cycles. No coatings. No planned obsolescence.',
    price: 145,
    images: [
      img('photo-1556911220-bff31c812dba'),
      img('photo-1604908176997-125f25cc6f3d'),
      img('photo-1506368249639-73a05d4d3072'),
    ],
    category: 'kitchen',
    brand: 'Field & Forge',
    material: 'Cast iron',
    materials: ['Cast iron', 'Flaxseed oil seasoning'],
    countryOfOrigin: 'USA',
    manufacturer: 'Field & Forge Foundry',
    warranty: 'Lifetime',
    expectedLifespan: '75+ years',
    longTermCostCheap: 480,
    longTermCostPremium: 175,
    cheapAlternativeName: 'Coated nonstick skillet',
    premiumYears: 75,
    pros: [
      'Improves with seasoning and daily use.',
      'Can be stripped and restored after neglect.',
      'Excellent heat retention for searing and baking.',
    ],
    cons: [
      'Heavy compared with aluminum pans.',
      'Requires drying and light oil after washing.',
    ],
    whoShouldBuy: [
      'Home cooks who want one pan for stovetop, oven, and campfire.',
      'Anyone tired of replacing scratched nonstick cookware.',
    ],
    whoShouldNotBuy: [
      'Cooks who need a very light pan.',
      'People unwilling to maintain seasoning.',
    ],
    sparePartsAvailable: false,
    repairable: true,
    repairabilityScore: 95,
    lifetimeScore: 98,
    overallRating: 4.9,
    scores: {
      lifetime: 98,
      repairability: 95,
      materialQuality: 96,
      manufacturerReputation: 94,
      warranty: 100,
    },
    badges: ['Lifetime Worthy', 'Lifetime Warranty', 'Repairable', "Editor's Pick", 'Made in USA'],
    whyWeChose:
      'Cast iron improves with use. This skillet is machined flat, heavy enough for heat retention, and simple enough to reseason forever. It will still cook well in 2050.',
    maintenance: [
      'Wash with hot water and a soft brush; avoid soap when possible.',
      'Dry thoroughly and wipe with a thin coat of oil.',
      'Reseason at 450°F if food begins to stick.',
    ],
    faq: [
      {
        q: 'Is it pre-seasoned?',
        a: 'Yes. It arrives ready to cook. Seasoning deepens with every meal.',
      },
      {
        q: 'Can it go in the oven?',
        a: 'Yes — oven-safe to 500°F. The handle stays cool longer than thin pans.',
      },
    ],
    variants: [
      { id: '10', title: '10 inch', available: true, price: 120 },
      { id: '12', title: '12 inch', available: true, price: 145 },
    ],
    inStock: true,
    featured: true,
    editorPick: true,
    shippingNote: 'Ships in 2–4 business days',
  },
  {
    id: 'pt-backpack',
    slug: 'full-grain-daypack',
    title: 'Full Grain Daypack',
    subtitle: 'Vegetable-tanned leather. Built for twenty years of commuting.',
    description:
      'A structured daypack in full-grain leather with solid brass hardware and a cotton canvas lining. Designed to develop a rich patina, not peel or crack like bonded leather.',
    price: 420,
    images: [
      img('photo-1553062407-98eeb64c6a62'),
      img('photo-1548036328-c9fa89d128fa'),
      img('photo-1622560480605-d83c853bc5c3'),
    ],
    category: 'travel',
    brand: 'Atelier North',
    material: 'Full grain leather',
    materials: ['Full grain leather', 'Solid brass', 'Cotton canvas'],
    countryOfOrigin: 'Italy',
    manufacturer: 'Atelier North',
    warranty: '10 years',
    expectedLifespan: '25+ years',
    longTermCostCheap: 640,
    longTermCostPremium: 520,
    cheapAlternativeName: 'Polyester commuter backpack',
    premiumYears: 25,
    pros: [
      'Hardware and straps can be repaired by leather shops.',
      'Full grain leather develops patina instead of peeling.',
      'Structured shape works for commuting and travel.',
    ],
    cons: [
      'Needs occasional conditioning.',
      'Heavier than nylon daypacks.',
    ],
    whoShouldBuy: [
      'Daily commuters who want a long-term carry piece.',
      'Travelers who value repairability over ultralight weight.',
    ],
    whoShouldNotBuy: [
      'Hikers who need a technical suspension system.',
      'Anyone who dislikes visible patina.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 92,
    lifetimeScore: 94,
    overallRating: 4.8,
    scores: {
      lifetime: 94,
      repairability: 92,
      materialQuality: 97,
      manufacturerReputation: 91,
      warranty: 88,
    },
    badges: ['Lifetime Worthy', 'Repairable', "Editor's Pick", 'Community Favorite'],
    whyWeChose:
      'Most backpacks fail at zippers and seams. This one uses replaceable brass hardware, thick leather panels, and a pattern that ages into character instead of wear.',
    maintenance: [
      'Condition leather twice a year with a neutral cream.',
      'Keep dry overnight if soaked; air dry away from heat.',
      'Hardware can be replaced by any leather workshop.',
    ],
    faq: [
      {
        q: 'Will the color darken?',
        a: 'Yes. Full grain leather deepens and softens with use — that is intended.',
      },
    ],
    variants: [
      { id: 'tan', title: 'Natural Tan', available: true },
      { id: 'black', title: 'Black', available: true },
    ],
    inStock: true,
    featured: true,
    editorPick: true,
  },
  {
    id: 'pt-chef-knife',
    slug: 'carbon-steel-gyuto',
    title: 'Carbon Steel Gyuto',
    subtitle: '210mm blade. Sharpens for a lifetime.',
    description:
      'A Japanese gyuto forged from high-carbon steel with a wa handle in magnolia and buffalo horn. Carbon steel takes a sharper edge than stainless and rewards care.',
    price: 285,
    images: [
      img('photo-1593618998160-e34014e67546'),
      img('photo-1566454825481-9c31bd4d803f'),
    ],
    category: 'kitchen',
    brand: 'Kuroba',
    material: 'Carbon steel / Magnolia',
    materials: ['High-carbon steel', 'Magnolia wood', 'Buffalo horn'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Kuroba Forge',
    warranty: 'Lifetime against defects',
    expectedLifespan: '40+ years',
    longTermCostCheap: 700,
    longTermCostPremium: 390,
    cheapAlternativeName: 'Stamped stainless chef knife',
    premiumYears: 40,
    pros: [
      'Takes a very fine edge and sharpens cleanly.',
      'Blade geometry can be thinned and repaired over time.',
      'Balanced for long prep sessions.',
    ],
    cons: [
      'Carbon steel will patina and can rust if left wet.',
      'Requires stone sharpening to get the most from it.',
    ],
    whoShouldBuy: [
      'Cooks who enjoy maintaining a serious knife.',
      'Anyone who values sharpenability over dishwasher convenience.',
    ],
    whoShouldNotBuy: [
      'Households that put knives in the dishwasher.',
      'Cooks who want zero-maintenance stainless steel.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 90,
    lifetimeScore: 96,
    overallRating: 4.9,
    scores: {
      lifetime: 96,
      repairability: 90,
      materialQuality: 98,
      manufacturerReputation: 95,
      warranty: 92,
    },
    badges: ['Lifetime Worthy', 'Made in Japan', 'Repairable', "Editor's Pick"],
    whyWeChose:
      'If a knife cannot be sharpened indefinitely, it is disposable. This gyuto is forged to be reshaped, repaired, and used for decades.',
    maintenance: [
      'Hand wash and dry immediately.',
      'Oil the blade lightly if storing unused.',
      'Hone before each use; stone-sharpen as needed.',
    ],
    faq: [
      {
        q: 'Will it rust?',
        a: 'Carbon steel can patina and spot if left wet. Wipe dry after use — the patina is part of its character.',
      },
    ],
    variants: [{ id: '210', title: '210mm', available: true }],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-wool-blanket',
    slug: 'heritage-wool-blanket',
    title: 'Heritage Wool Blanket',
    subtitle: 'Heavyweight virgin wool. Warmth without obsolescence.',
    description:
      'A tightly woven virgin wool blanket with whipstitch edges. Naturally flame-resistant, odor-resistant, and repairable by any capable tailor.',
    price: 265,
    images: [
      img('photo-1631679706909-1844c1f6b6d3'),
      img('photo-1584100936595-c0654b55a2e2'),
    ],
    category: 'home',
    brand: 'North Loom',
    material: 'Virgin wool',
    materials: ['Virgin wool', 'Cotton whipstitch'],
    countryOfOrigin: 'Scotland',
    manufacturer: 'North Loom Mills',
    warranty: '25 years',
    expectedLifespan: '40+ years',
    longTermCostCheap: 540,
    longTermCostPremium: 325,
    cheapAlternativeName: 'Acrylic throw blanket',
    premiumYears: 40,
    pros: [
      'Naturally warm, odor resistant, and flame resistant.',
      'Can be darned or edge-repaired by a tailor.',
      'Classic pattern works across rooms and seasons.',
    ],
    cons: [
      'Requires careful cleaning.',
      'May feel scratchy to wool-sensitive users.',
    ],
    whoShouldBuy: [
      'People who want one reliable blanket for bed, sofa, and cabin.',
      'Anyone replacing pilling synthetic throws.',
    ],
    whoShouldNotBuy: [
      'People with wool sensitivity.',
      'Buyers who need machine-wash convenience.',
    ],
    sparePartsAvailable: false,
    repairable: true,
    repairabilityScore: 88,
    lifetimeScore: 93,
    overallRating: 4.7,
    scores: {
      lifetime: 93,
      repairability: 88,
      materialQuality: 94,
      manufacturerReputation: 90,
      warranty: 90,
    },
    badges: ['Lifetime Worthy', 'Best Value', 'Community Favorite'],
    whyWeChose:
      'Synthetics pill and shed microplastics. This wool blanket can be cleaned, darned, and passed down — it does not need replacing every few winters.',
    maintenance: [
      'Air outdoors seasonally.',
      'Spot clean; professional clean when needed.',
      'Store with cedar, not mothballs.',
    ],
    faq: [],
    variants: [
      { id: 'grey', title: 'Heather Grey', available: true },
      { id: 'forest', title: 'Forest', available: false },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-mechanic-tool',
    slug: 'socket-set-chrome-vanadium',
    title: 'Chrome Vanadium Socket Set',
    subtitle: '72-tooth ratchet. Tools you buy once.',
    description:
      'A complete metric/SAE socket set in chrome vanadium steel with a lifetime replacement guarantee. Foam-lined case. No chrome flaking. No plastic ratchets.',
    price: 198,
    images: [
      img('photo-1530124566582-a618bc2615dc'),
      img('photo-1504148455328-c376907d081c'),
    ],
    category: 'tools',
    brand: 'Forgewright',
    material: 'Chrome vanadium steel',
    materials: ['Chrome vanadium steel', 'Chrome plating', 'Glass-filled nylon case'],
    countryOfOrigin: 'Germany',
    manufacturer: 'Forgewright GmbH',
    warranty: 'Lifetime',
    expectedLifespan: '50+ years',
    longTermCostCheap: 450,
    longTermCostPremium: 230,
    cheapAlternativeName: 'Budget socket set',
    premiumYears: 50,
    pros: [
      'Precise sockets reduce rounded fasteners.',
      'Ratchet rebuild kits and replacements are available.',
      'Lifetime warranty covers professional use.',
    ],
    cons: [
      'Costs more than big-box starter sets.',
      'Foam case takes more storage room.',
    ],
    whoShouldBuy: [
      'Home mechanics building a permanent tool kit.',
      'Professionals who need warranty support.',
    ],
    whoShouldNotBuy: [
      'Apartment dwellers who only assemble flat-pack furniture.',
      'Anyone who needs a compact travel kit.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 85,
    lifetimeScore: 97,
    overallRating: 4.8,
    scores: {
      lifetime: 97,
      repairability: 85,
      materialQuality: 95,
      manufacturerReputation: 93,
      warranty: 100,
    },
    badges: ['Lifetime Worthy', 'Lifetime Warranty', 'Made in Germany', 'Best Value', 'Repairable'],
    whyWeChose:
      'Cheap tool sets fail at the ratchet. This one is rebuildable, warrantied for life, and precise enough for professional work.',
    maintenance: ['Wipe clean after use.', 'Light oil on ratchet mechanism yearly.'],
    faq: [],
    variants: [{ id: 'full', title: 'Full Set', available: true }],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-notebook',
    slug: 'linen-hardcover-notebook',
    title: 'Linen Hardcover Notebook',
    subtitle: 'Archival paper. A notebook worth keeping.',
    description:
      'Lay-flat binding, fountain-pen friendly paper, and a linen cover that ages gracefully. Designed as a lasting record, not a disposable pad.',
    price: 48,
    images: [
      img('photo-1531346878377-a5be20888e57'),
      img('photo-1517842645767-c639042777db'),
    ],
    category: 'writing',
    brand: 'Plain & Ruled',
    material: 'Linen / Archival paper',
    materials: ['Linen book cloth', 'Acid-free paper', 'Thread-sewn binding'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Plain & Ruled',
    warranty: '1 year',
    expectedLifespan: '100+ years as an archive',
    longTermCostCheap: 180,
    longTermCostPremium: 96,
    cheapAlternativeName: 'Glue-bound notebook',
    premiumYears: 100,
    pros: [
      'Sewn binding lies flat and resists page loss.',
      'Archival paper preserves ink and pencil notes.',
      'Works well with fountain pens.',
    ],
    cons: [
      'Pages are not refillable.',
      'Higher upfront cost for a consumable object.',
    ],
    whoShouldBuy: [
      'Writers and planners who keep long-term records.',
      'Fountain pen users who need paper that will not feather.',
    ],
    whoShouldNotBuy: [
      'People who discard notebooks after projects.',
      'Anyone who wants perforated tear-out pages.',
    ],
    sparePartsAvailable: false,
    repairable: false,
    repairabilityScore: 70,
    lifetimeScore: 85,
    overallRating: 4.6,
    scores: {
      lifetime: 85,
      repairability: 70,
      materialQuality: 90,
      manufacturerReputation: 88,
      warranty: 60,
    },
    badges: ['Made in Japan', "Editor's Pick", 'Best Value'],
    whyWeChose:
      'Most notebooks yellow and fall apart. Archival paper and sewn binding mean your notes remain readable for decades.',
    maintenance: ['Store flat away from humidity.'],
    faq: [],
    variants: [
      { id: 'a5', title: 'A5 Lined', available: true },
      { id: 'a5dot', title: 'A5 Dot', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-thermos',
    slug: 'double-wall-steel-flask',
    title: 'Double-Wall Steel Flask',
    subtitle: '24 hours cold. A lifetime of refills.',
    description:
      '18/8 stainless steel, vacuum insulated, with a replaceable gasket and a lid designed to be serviced — not thrown away.',
    price: 68,
    images: [
      img('photo-1602143407151-7111542de6e8'),
      img('photo-1523362628745-0c100150b504'),
    ],
    category: 'outdoors',
    brand: 'Trail Keep',
    material: '18/8 stainless steel',
    materials: ['18/8 stainless steel', 'Silicone gasket', 'BPA-free polypropylene lid'],
    countryOfOrigin: 'USA',
    manufacturer: 'Trail Keep',
    warranty: 'Lifetime',
    expectedLifespan: '30+ years',
    longTermCostCheap: 360,
    longTermCostPremium: 108,
    cheapAlternativeName: 'Plastic water bottle',
    premiumYears: 30,
    pros: [
      'Replaceable gasket prevents lid failure from ending the bottle.',
      'Keeps coffee hot and water cold through a full day.',
      'Dents rarely affect function.',
    ],
    cons: [
      'Lid parts need hand washing.',
      'Narrow mouth is slower to fill with ice.',
    ],
    whoShouldBuy: [
      'Commuters, campers, and drivers who carry drinks daily.',
      'Anyone replacing disposable bottles or fragile tumblers.',
    ],
    whoShouldNotBuy: [
      'People who only want dishwasher-safe lids.',
      'Ultralight backpackers counting every ounce.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 91,
    lifetimeScore: 95,
    overallRating: 4.7,
    scores: {
      lifetime: 95,
      repairability: 91,
      materialQuality: 93,
      manufacturerReputation: 89,
      warranty: 100,
    },
    badges: ['Lifetime Worthy', 'Lifetime Warranty', 'Repairable', 'Made in USA', 'Field Tested'],
    whyWeChose:
      'Most bottles fail when the seal wears out. Trail Keep sells replacement gaskets — the flask itself should outlast you.',
    maintenance: [
      'Hand wash; avoid dishwashers for the lid.',
      'Replace gasket every few years.',
    ],
    faq: [],
    variants: [
      { id: '500', title: '500ml', available: true },
      { id: '750', title: '750ml', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-desk-lamp',
    slug: 'brass-task-lamp',
    title: 'Brass Task Lamp',
    subtitle: 'Weighted base. Replaceable bulb. Timeless form.',
    description:
      'A machined brass task lamp with a fabric cord and a standard E26 socket. Built to be rewired, repolished, and kept on the desk for decades.',
    price: 310,
    images: [
      img('photo-1507473885765-e6ed057f782c'),
      img('photo-1513506003901-1e6a229e2d15'),
    ],
    category: 'office',
    brand: 'Studio Meridian',
    material: 'Solid brass',
    materials: ['Solid brass', 'Steel armature', 'Cloth-covered cord'],
    countryOfOrigin: 'USA',
    manufacturer: 'Studio Meridian',
    warranty: '15 years',
    expectedLifespan: '40+ years',
    longTermCostCheap: 520,
    longTermCostPremium: 370,
    cheapAlternativeName: 'Integrated LED desk lamp',
    premiumYears: 40,
    pros: [
      'Standard socket avoids sealed LED-driver failure.',
      'Brass can be polished, repatinated, and rewired.',
      'Stable weighted base feels permanent on a desk.',
    ],
    cons: [
      'Brass patina is visible unless polished.',
      'Costs more than molded desk lamps.',
    ],
    whoShouldBuy: [
      'Readers and desk workers who want serviceable lighting.',
      'People furnishing an office for the long term.',
    ],
    whoShouldNotBuy: [
      'Anyone who wants app-controlled smart lighting.',
      'Buyers who dislike metal patina.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 94,
    lifetimeScore: 96,
    overallRating: 4.8,
    scores: {
      lifetime: 96,
      repairability: 94,
      materialQuality: 97,
      manufacturerReputation: 90,
      warranty: 85,
    },
    badges: ['Lifetime Worthy', 'Repairable', 'Made in USA', "Editor's Pick", 'Premium Choice'],
    whyWeChose:
      'LED-integrated lamps die with their drivers. This lamp uses replaceable bulbs and serviceable wiring — light that lasts as long as brass does.',
    maintenance: [
      'Polish brass as desired, or let it patina.',
      'Any electrician can rewire the cord.',
    ],
    faq: [],
    variants: [
      { id: 'natural', title: 'Natural Brass', available: true },
      { id: 'blackened', title: 'Blackened Brass', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-flashlight',
    slug: 'aircraft-aluminum-flashlight',
    title: 'Aircraft Aluminum Flashlight',
    subtitle: 'Serviceable LED module, sealed for storms.',
    description:
      'A compact everyday flashlight machined from hard-anodized aircraft aluminum with a replaceable lens, tail switch, o-rings, and rechargeable cell.',
    price: 118,
    images: [
      img('photo-1516280440614-37939bbacd81'),
      img('photo-1500530855697-b586d89ba3ee'),
    ],
    category: 'everyday-carry',
    brand: 'Lumen Works',
    material: 'Hard-anodized aluminum',
    materials: ['6061 aluminum', 'Tempered glass', 'Silicone o-rings'],
    countryOfOrigin: 'USA',
    manufacturer: 'Lumen Works',
    warranty: 'Lifetime',
    expectedLifespan: '25+ years',
    longTermCostCheap: 420,
    longTermCostPremium: 170,
    cheapAlternativeName: 'Disposable alkaline flashlight',
    premiumYears: 25,
    pros: [
      'Tail switch, lens, clip, and seals are replaceable.',
      'Common rechargeable cell avoids proprietary battery waste.',
      'Bright enough for home, travel, and roadside work.',
    ],
    cons: [
      'More expensive than plastic emergency lights.',
      'High-output mode drains batteries quickly.',
    ],
    whoShouldBuy: [
      'Anyone building a dependable everyday carry kit.',
      'Campers and homeowners who need a light that can be serviced.',
    ],
    whoShouldNotBuy: [
      'People who only need an occasional junk-drawer light.',
      'Buyers who want built-in USB charging above all else.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 93,
    lifetimeScore: 94,
    overallRating: 4.8,
    scores: {
      lifetime: 94,
      repairability: 93,
      materialQuality: 92,
      manufacturerReputation: 90,
      warranty: 100,
    },
    badges: ['Lifetime Warranty', 'Repairable', 'Made in USA', 'Field Tested', 'Best Value'],
    whyWeChose:
      'Most flashlights become trash when a switch or seal fails. This one is designed around standard cells and replaceable wear parts.',
    maintenance: [
      'Clean battery contacts yearly.',
      'Lubricate o-rings after heavy rain or dusty use.',
      'Store with a partially charged cell.',
    ],
    faq: [
      {
        q: 'Can the battery be replaced?',
        a: 'Yes. It uses a common rechargeable cell available from multiple makers.',
      },
    ],
    variants: [
      { id: 'black', title: 'Matte Black', available: true },
      { id: 'natural', title: 'Natural Aluminum', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-french-press',
    slug: 'stainless-french-press',
    title: 'Stainless French Press',
    subtitle: 'Double-wall steel with replaceable mesh and glass-free service.',
    description:
      'A thermal French press made from 18/8 stainless steel with a rebuildable plunger, replaceable mesh filters, and a no-chip body for daily coffee.',
    price: 96,
    images: [
      img('photo-1495474472287-4d71bcdd2085'),
      img('photo-1509042239860-f550ce710b93'),
    ],
    category: 'coffee',
    brand: 'North Star Coffee Tools',
    material: '18/8 stainless steel',
    materials: ['18/8 stainless steel', 'Stainless mesh', 'Silicone gasket'],
    countryOfOrigin: 'Germany',
    manufacturer: 'North Star Werkstatt',
    warranty: '20 years',
    expectedLifespan: '20+ years',
    longTermCostCheap: 300,
    longTermCostPremium: 136,
    cheapAlternativeName: 'Glass French press',
    premiumYears: 20,
    pros: [
      'No glass carafe to crack in the sink.',
      'Mesh filters and seals are inexpensive to replace.',
      'Double-wall body keeps coffee warm longer.',
    ],
    cons: [
      'Heavier than glass presses.',
      'You cannot see the brew level through the body.',
    ],
    whoShouldBuy: [
      'Daily coffee drinkers who have broken glass presses before.',
      'Campers and hosts who need durable batch brewing.',
    ],
    whoShouldNotBuy: [
      'Pour-over loyalists who prefer paper filtration.',
      'People who want a transparent carafe.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 92,
    lifetimeScore: 93,
    overallRating: 4.7,
    scores: {
      lifetime: 93,
      repairability: 92,
      materialQuality: 91,
      manufacturerReputation: 88,
      warranty: 90,
    },
    badges: ['Repairable', 'Made in Germany', 'Best Value', 'Community Favorite'],
    whyWeChose:
      'A French press should not be disposable glassware. Stainless construction and replaceable screens make this a coffee tool you can rebuild.',
    maintenance: [
      'Disassemble and rinse the plunger weekly.',
      'Replace mesh when fines increase in the cup.',
      'Use baking soda to remove coffee oils from steel.',
    ],
    faq: [
      {
        q: 'Does it keep coffee hot?',
        a: 'The double-wall body holds heat far longer than glass, though coffee still tastes best fresh.',
      },
    ],
    variants: [
      { id: '750', title: '750ml', available: true },
      { id: '1000', title: '1 liter', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-pruners',
    slug: 'forged-bypass-pruners',
    title: 'Forged Bypass Pruners',
    subtitle: 'Replaceable blade, spring, and latch for decades in the garden.',
    description:
      'Drop-forged bypass pruners with hardened steel blades, a replaceable spring, brass lock, and handles shaped for all-day pruning.',
    price: 84,
    images: [
      img('photo-1416879595882-3373a0480b5b'),
      img('photo-1523348837708-15d4a09cfac2'),
    ],
    category: 'garden',
    brand: 'Oak & Orchard',
    material: 'Drop-forged steel',
    materials: ['Hardened carbon steel', 'Forged aluminum handles', 'Brass latch'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Oak & Orchard Toolworks',
    warranty: 'Lifetime against defects',
    expectedLifespan: '30+ years',
    longTermCostCheap: 280,
    longTermCostPremium: 124,
    cheapAlternativeName: 'Stamped garden pruners',
    premiumYears: 30,
    pros: [
      'Blade, spring, bumper, and latch can be replaced.',
      'Forged handles resist flex and keep cuts clean.',
      'Easy to sharpen with a small stone.',
    ],
    cons: [
      'Needs cleaning after sap-heavy pruning.',
      'May be too small for very large hands.',
    ],
    whoShouldBuy: [
      'Gardeners who prune roses, fruit trees, and shrubs every season.',
      'Anyone who wants a tool that can be rebuilt instead of replaced.',
    ],
    whoShouldNotBuy: [
      'People who only cut thick branches needing loppers.',
      'Buyers who will not clean or oil blades.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 96,
    lifetimeScore: 95,
    overallRating: 4.9,
    scores: {
      lifetime: 95,
      repairability: 96,
      materialQuality: 94,
      manufacturerReputation: 92,
      warranty: 92,
    },
    badges: ['Lifetime Worthy', 'Repairable', 'Made in Japan', "Editor's Pick"],
    whyWeChose:
      'Garden pruners live hard lives. Replaceable blades and springs mean a season of sap and grit is maintenance, not the end.',
    maintenance: [
      'Wipe sap from the blade after use.',
      'Oil the pivot monthly during pruning season.',
      'Sharpen the bevel lightly before spring growth.',
    ],
    faq: [
      {
        q: 'Can left-handed gardeners use them?',
        a: 'The standard model is right-handed; a left-handed variant is available.',
      },
    ],
    variants: [
      { id: 'right', title: 'Right-handed', available: true },
      { id: 'left', title: 'Left-handed', available: true },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: 'pt-tripod',
    slug: 'all-metal-travel-tripod',
    title: 'All-Metal Travel Tripod',
    subtitle: 'Aluminum legs, rebuildable locks, and a standard head mount.',
    description:
      'A compact photography tripod with machined aluminum legs, serviceable twist locks, replaceable feet, and a standard 3/8-inch head mount.',
    price: 245,
    images: [
      img('photo-1516035069371-29a1b244cc32'),
      img('photo-1500530855697-b586d89ba3ee'),
    ],
    category: 'photography',
    brand: 'Aperture Foundry',
    material: 'Machined aluminum',
    materials: ['Machined aluminum', 'Stainless hardware', 'Rubber feet'],
    countryOfOrigin: 'USA',
    manufacturer: 'Aperture Foundry',
    warranty: 'Lifetime service program',
    expectedLifespan: '25+ years',
    longTermCostCheap: 600,
    longTermCostPremium: 315,
    cheapAlternativeName: 'Plastic travel tripod',
    premiumYears: 25,
    pros: [
      'Locks can be cleaned, relubricated, and rebuilt.',
      'Standard head mount avoids proprietary plates.',
      'Stable enough for long exposures and field work.',
    ],
    cons: [
      'Not as light as carbon fiber ultralight tripods.',
      'Requires occasional cleaning after sand or saltwater.',
    ],
    whoShouldBuy: [
      'Photographers who travel but still need real stability.',
      'Video creators who want standard mounts and serviceable locks.',
    ],
    whoShouldNotBuy: [
      'Backpackers who need the lightest possible support.',
      'Casual phone shooters who rarely use a tripod.',
    ],
    sparePartsAvailable: true,
    repairable: true,
    repairabilityScore: 90,
    lifetimeScore: 92,
    overallRating: 4.7,
    scores: {
      lifetime: 92,
      repairability: 90,
      materialQuality: 93,
      manufacturerReputation: 88,
      warranty: 95,
    },
    badges: ['Repairable', 'Made in USA', 'Field Tested', 'Premium Choice'],
    whyWeChose:
      'Tripods fail at locks, feet, and proprietary heads. This model keeps every wear point accessible and replaceable.',
    maintenance: [
      'Rinse and dry legs after beach use.',
      'Clean grit from twist locks before storage.',
      'Replace rubber feet when tread wears smooth.',
    ],
    faq: [
      {
        q: 'Does it include a ball head?',
        a: 'Yes, and the standard mount lets you replace it with any compatible head later.',
      },
    ],
    variants: [
      { id: 'aluminum', title: 'Aluminum', available: true },
      { id: 'tall', title: 'Tall Aluminum', available: true },
    ],
    inStock: true,
    featured: true,
  },
];

export const articles: Article[] = [
  {
    slug: 'why-cast-iron-beats-nonstick',
    title: 'Why Cast Iron Beats Nonstick',
    excerpt:
      'Coatings fail. Iron improves. A clear case for cookware that gets better with time.',
    cover: img('photo-1556911220-bff31c812dba'),
    author: {
      name: 'Elena Marsh',
      role: 'Editor',
      avatar: img('photo-1494790108377-be9c29b29330', 200),
    },
    publishedAt: '2026-03-12',
    tags: ['Kitchen', 'Materials'],
    body: [
      'Nonstick pans are designed to be replaced. Their coatings degrade, flake, and eventually fail — often within a few years of regular use.',
      'Cast iron asks for attention, not replacement. Seasoning builds a natural cooking surface that improves with heat cycles. Scratches do not ruin it. They become part of its history.',
      'When you buy a well-made skillet, you are buying decades of meals — and a tool your children can inherit.',
    ],
  },
  {
    slug: 'the-last-backpack-youll-ever-buy',
    title: "The Last Backpack You'll Ever Buy",
    excerpt:
      'What separates a bag that lasts two years from one that lasts twenty.',
    cover: img('photo-1553062407-98eeb64c6a62'),
    author: {
      name: 'Jonah Reed',
      role: 'Product Lead',
      avatar: img('photo-1507003211169-0a1dd7228f2d', 200),
    },
    publishedAt: '2026-02-28',
    tags: ['Travel', 'Leather'],
    body: [
      'Most backpacks fail quietly: a zipper tooth, a frayed strap, a foam panel that collapses. The product looks fine until it suddenly is not.',
      'A buy-it-for-life bag is repairable by design. Hardware can be replaced. Leather can be conditioned. Seams are built for stress, not for a season.',
      'Pay more once. Carry it for decades.',
    ],
  },
  {
    slug: 'the-beauty-of-full-grain-leather',
    title: 'The Beauty of Full Grain Leather',
    excerpt: 'Patina is not damage. It is proof of a material that lasts.',
    cover: img('photo-1548036328-c9fa89d128fa'),
    author: {
      name: 'Elena Marsh',
      role: 'Editor',
      avatar: img('photo-1494790108377-be9c29b29330', 200),
    },
    publishedAt: '2026-01-18',
    tags: ['Materials'],
    body: [
      'Full grain leather keeps the natural surface of the hide. It scratches, darkens, and softens — and grows more beautiful for it.',
      'Corrected grain and bonded leather try to look perfect forever. They peel instead.',
    ],
  },
  {
    slug: 'things-worth-buying-once',
    title: 'Things Worth Buying Once',
    excerpt: 'A shortlist of objects that repay their cost in years of use.',
    cover: img('photo-1616486338812-3dadae4b4ace'),
    author: {
      name: 'Sam Okonkwo',
      role: 'Curator',
      avatar: img('photo-1472099645785-5658abf4ff4e', 200),
    },
    publishedAt: '2025-12-04',
    tags: ['Philosophy'],
    body: [
      'Buying once is not about luxury. It is about refusing the cycle of cheap replacements.',
      'The right knife, blanket, lamp, or tool can remove dozens of future purchases from your life.',
    ],
  },
  {
    slug: 'repair-instead-of-replace',
    title: 'Repair Instead of Replace',
    excerpt: 'Repairability is the most honest measure of quality.',
    cover: img('photo-1581091226825-a6a2a5aee158'),
    author: {
      name: 'Jonah Reed',
      role: 'Product Lead',
      avatar: img('photo-1507003211169-0a1dd7228f2d', 200),
    },
    publishedAt: '2025-11-09',
    tags: ['Repair', 'Philosophy'],
    body: [
      'If a product cannot be opened, serviced, or parts-replaced, it was designed to be discarded.',
      'We score every product for repairability — because longevity without repair is just marketing.',
    ],
  },
  {
    slug: 'how-to-calculate-cost-per-year',
    title: 'How to Calculate Cost Per Year',
    excerpt:
      'The simplest way to compare a cheap product with a premium one is to divide by useful years.',
    cover: img('photo-1554224155-6726b3ff858f'),
    author: {
      name: 'Sam Okonkwo',
      role: 'Curator',
      avatar: img('photo-1472099645785-5658abf4ff4e', 200),
    },
    publishedAt: '2025-10-21',
    tags: ['Buying Guide', 'Value'],
    body: [
      'A low price can hide a high ownership cost. If a $40 item fails every two years, it costs $400 over twenty years before frustration, shipping, and waste.',
      'A better object can still be expensive. The question is whether materials, repair paths, warranty, and real lifespan support the premium.',
      'We publish long-term cost comparisons because the practical choice is rarely the cheapest checkout price.',
    ],
  },
  {
    slug: 'a-seasonal-maintenance-checklist',
    title: 'A Seasonal Maintenance Checklist for Things That Last',
    excerpt:
      'Small rituals for leather, steel, wool, wood, and mechanical parts that prevent big repairs later.',
    cover: img('photo-1581091226825-a6a2a5aee158'),
    author: {
      name: 'Elena Marsh',
      role: 'Editor',
      avatar: img('photo-1494790108377-be9c29b29330', 200),
    },
    publishedAt: '2025-09-14',
    tags: ['Maintenance', 'Repair'],
    body: [
      'Durable products are not maintenance-free. They are maintenance-worthy. A few minutes each season keeps leather from drying, steel from rusting, and wool safe from moths.',
      'Build a small kit: mineral oil, leather conditioner, a sharpening stone, a soft brush, spare o-rings, and cedar blocks. Most care tasks become simple when supplies are already nearby.',
      'Maintenance is ownership, not a chore. It is how good things stay good.',
    ],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    name: 'Marcus T.',
    location: 'Portland, OR',
    quote:
      'I bought the skillet three years ago. It cooks better now than the day it arrived.',
    product: 'Heirloom Cast Iron Skillet',
    image: img('photo-1556911220-bff31c812dba', 800),
    rating: 5,
  },
  {
    id: 'r2',
    name: 'Priya N.',
    location: 'Brooklyn, NY',
    quote:
      'The daypack has become part of my uniform. Scuffs look intentional. Hardware still perfect.',
    product: 'Full Grain Daypack',
    image: img('photo-1553062407-98eeb64c6a62', 800),
    rating: 5,
  },
  {
    id: 'r3',
    name: 'Daniel K.',
    location: 'Austin, TX',
    quote:
      'Finally a tool set I trust enough to lend — and know I will get back intact.',
    product: 'Chrome Vanadium Socket Set',
    image: img('photo-1530124566582-a618bc2615dc', 800),
    rating: 5,
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getArticle(slug: string) {
  return articles.find((a) => a.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return products.filter((p) => p.category === slug);
}

export function searchCatalog(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return { products: [], articles: [] };
  return {
    products: products.filter((p) =>
      [
        p.title,
        p.brand,
        p.material,
        ...(p.materials || []),
        p.category,
        p.countryOfOrigin,
        p.expectedLifespan,
        p.cheapAlternativeName,
        ...p.pros,
        ...p.cons,
        ...p.whoShouldBuy,
        ...p.whoShouldNotBuy,
      ]
        .join(' ')
        .toLowerCase()
        .includes(q),
    ),
    articles: articles.filter((a) =>
      [a.title, a.excerpt, ...a.tags].join(' ').toLowerCase().includes(q),
    ),
  };
}
