[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @practical-things/storefront build"]

[start]
cmd = "node .next/standalone/apps/storefront/server.js"
